### ISSUE TITLE
我小白，想试试这个工具，麻烦您了，下载不到了

### ISSUE THREAD

**Issue by wanghao008** [Lotus6/ThinkLog#2]
我小白，想试试这个工具，麻烦您了，下载不到了

**Comment by Lotus6** [comment]
点击release下载



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wanghao008 ***@***.***&gt;
发送时间: 2022年5月23日 16:44
收件人: Lotus6/ThinkLog ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Lotus6/ThinkLog] 我小白，想试试这个工具，麻烦您了，下载不到了 (Issue #2)





 
我小白，想试试这个工具，麻烦您了，下载不到了

**Comment by wanghao008** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lotus6/ThinkLog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 凌晨1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lotus6/ThinkLog] 我小白，想试试这个工具，麻烦您了，下载不到了 (Issue #2)





 点击release下载 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: wanghao008 ***@***.***&amp;gt; 
 发送时间: 2022年5月23日 16:44 
 收件人: Lotus6/ThinkLog ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[Lotus6/ThinkLog] 我小白，想试试这个工具，麻烦您了，下载不到了 (Issue #2) 
 
 
 
 
 
   
 我小白，想试试这个工具，麻烦您了，下载不到了
